### ISSUE TITLE
About Architecture

### ISSUE THREAD

**Issue by grewalshelly** [gmershad/FoodDeliveryApp#3]
HI,

May I ask you What architecture you used for your software. 

Thanks

**Comment by gmershad** [comment]
Hello,

We generally use micro-service oriented architecture for our software.

Regards,
Gul Ershad

**Comment by grewalshelly** [comment]
Hi Gul,
Thanks for your reply. I have some more qeries about this project . Can I ask your email please?

**Comment by gmershad** [comment]
mailtogulershad@gmail.com
