### ISSUE TITLE
Backend File

### ISSUE THREAD

**Issue by grewalshelly** [gmershad/FoodDeliveryApp#4]
Hi,

Can you please describe about this project?
1. Did you use any database in this project?
2. If not then How this project runs without database.
3. Did you use any API or reference file to run the project?

**Comment by gmershad** [comment]
Please find below information:
1. No, this project doesn't use any database. But, you can extend it and create interfaces for the database interaction.

2. This is a kind of standalone console application and doesn't expose any rest API.

Idea of this project is to demonstrate the working flow of Food delivery application by using real object oriented approach with different types of design pattern. However, the logic of this project easily fits with Micro-Services or Service Oriented Architecture (SOA). 
It provides full abstracted, cohesive and loose coupled way of code.
