### ISSUE TITLE
Bootstrap tour

### ISSUE THREAD

**Issue by u-stack** [gmershad/FoodDeliveryApp#7]
I have two tours on the same page both of them are working fine but I have diagnosed a problem that when I started tour1 and I reached  step 3 or 4 or 5 any step so on that point without ending that tour when I start tour2 it started from that step where tour1 was left as it starts from its step 3 or 4 or 5 i need solution for this kindly help

**Comment by gmershad** [comment]
This is not a relevant issue for this project.

**Comment by u-stack** [comment]
why is this not relevent i am facing problem kindly help

**Comment by u-stack** [comment]
> This is not a relevant issue for this project.

if you did not understand what am trying to say i can provide you the video of issue
